### ISSUE TITLE
Different types for name in TopicCreated events

### ISSUE THREAD

**Issue by frankobe** [bodhiproject/bodhi-core#35]
in EventFactory, name is type: `byte32[10]`
https://github.com/bodhiproject/bodhi-core/blob/master/contracts/events/EventFactory.sol#L11

in TopicEvent, name is type: `string`
https://github.com/bodhiproject/bodhi-core/blob/master/contracts/events/TopicEvent.sol#L26

**Comment by dwalintukan** [comment]
This is intentional because of two reasons:
1. If I converted it to `string` in `EventFactory` I would not be able to pass it to `TopicEvent`s constructor. (strings are not allowable function params currently)
2. I would only be converting `bytes32[10]` to `string` in `EventFactory` for the purpose of using it for the Event. If I did, then it would also increase the gas usage of the `createTopic()` function. And converting the bytes[] to string for just an Event emit, from an efficiency standpoint is not worth the extra gas IMO.

But if you want to have a single parsing method for `TopicCreated` events that will work on both I understand and I can change to a `string` in EventFactory. Let me know.

**Comment by frankhu-optimizely** [comment]
@dwalintukan 
1. We can remove one event as two of them log similar information when creating events. 
2. For `_name` attribute, `byte32[10]` should be ok
3. I am confused on how `byte32[10]` can represent a `string` (_name) and an array of `string` (_resultNames) at the same time

**Comment by dwalintukan** [comment]
@frankhu-optimizely 
1. Ok that sounds fine with me. Going to remove the `TopicCreated` in `TopicEvent` as it makes more sense to watch it at the factory level.
3. `bytes32[10]` can be converted into a `string` by putting all the bytes together then converting it to a `string`.

**Comment by dwalintukan** [comment]
@frankobe is this resolved?
