### ISSUE TITLE
Users staking token when creating events

### ISSUE THREAD

**Issue by frankobe** [bodhiproject/bodhi-core#85]

**Comment by dwalintukan** [comment]
Discussed with TT. This will be held off for now.

If we move the staking to the creation of the event, there is no incentive for the Centralized Oracle to set the result. The original thought was to prevent creation of many unnecessary markets (spam). But if the person who created the event (ie. also the Centralized Oracle) didn't set the result, they would get refunded back. So there is no disadvantage of creating these spam events since they will get their BOT back anyways.
